# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rosqpSetup <- function(P, q, A, l, u, pars) {
    .Call(`_rosqp_rosqpSetup`, P, q, A, l, u, pars)
}

rosqpSolve <- function(workPtr) {
    .Call(`_rosqp_rosqpSolve`, workPtr)
}

rosqpGetParams <- function(workPtr) {
    .Call(`_rosqp_rosqpGetParams`, workPtr)
}

rosqpGetDims <- function(workPtr) {
    .Call(`_rosqp_rosqpGetDims`, workPtr)
}

rosqpUpdate <- function(workPtr, q_new, l_new, u_new) {
    invisible(.Call(`_rosqp_rosqpUpdate`, workPtr, q_new, l_new, u_new))
}

rosqpUpdateSettings <- function(workPtr, val, nm) {
    invisible(.Call(`_rosqp_rosqpUpdateSettings`, workPtr, val, nm))
}

rosqpGetData <- function(workPtr, nm) {
    .Call(`_rosqp_rosqpGetData`, workPtr, nm)
}

rosqpWarmStart <- function(workPtr, x, y) {
    invisible(.Call(`_rosqp_rosqpWarmStart`, workPtr, x, y))
}

