# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

osqpSetup <- function(P, q, A, l, u, pars) {
    .Call(`_osqp_osqpSetup`, P, q, A, l, u, pars)
}

osqpSolve <- function(workPtr) {
    .Call(`_osqp_osqpSolve`, workPtr)
}

osqpGetParams <- function(workPtr) {
    .Call(`_osqp_osqpGetParams`, workPtr)
}

osqpGetDims <- function(workPtr) {
    .Call(`_osqp_osqpGetDims`, workPtr)
}

osqpUpdate <- function(workPtr, q_new, l_new, u_new, Px, Px_idx, Ax, Ax_idx) {
    invisible(.Call(`_osqp_osqpUpdate`, workPtr, q_new, l_new, u_new, Px, Px_idx, Ax, Ax_idx))
}

osqpUpdateSettings <- function(workPtr, val, nm) {
    invisible(.Call(`_osqp_osqpUpdateSettings`, workPtr, val, nm))
}

osqpGetData <- function(workPtr, nm) {
    .Call(`_osqp_osqpGetData`, workPtr, nm)
}

osqpWarmStart <- function(workPtr, x, y) {
    invisible(.Call(`_osqp_osqpWarmStart`, workPtr, x, y))
}

